# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-26 18:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercourse',
            options={'verbose_name': '\u7528\u6237\u8bfe\u7a0b', 'verbose_name_plural': '\u7528\u6237\u8bfe\u7a0b'},
        ),
        migrations.RenameField(
            model_name='usercourse',
            old_name='course',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237\u540d'),
        ),
    ]
