# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-26 18:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20170726_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercourse',
            old_name='name',
            new_name='course',
        ),
    ]
