# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-27 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='vedio',
            name='url',
            field=models.CharField(default='', max_length=100, verbose_name='\u89c6\u9891\u8bbf\u95ee'),
        ),
    ]
