# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-27 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20170727_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='learn_times',
            field=models.IntegerField(default=30, verbose_name='\u5b66\u4e60\u65f6\u957f(\u5206\u949f\u6570)'),
        ),
    ]
