# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-27 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20170727_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.CharField(default='', max_length=300, verbose_name='\u89c6\u9891\u8bbf\u95ee'),
        ),
    ]
